import { FetchFieldNames } from "../../service-clients/wize-database-service-client";
import { getSelectedClientFromCookies } from "@/context/clientActions";
import { redirect } from "next/navigation";
import NavigateBackButton from '@/app/components/NavigateBackButton';

type SearchParams = {
  db: string;
  table: string;
};

export default async function AdminCreatePage({ searchParams }: { searchParams: SearchParams }) {
  const { db, table } = searchParams;
  
  // Get the selected client from cookies
  const selectedClient = await getSelectedClientFromCookies();
  
  // Check if user is admin (client value is '0')
  if (!selectedClient || selectedClient.value !== '0') {
    // Non-admin users or no client selected - redirect to databases page
    redirect('/databases');
  }
  
  // Admin user - continue with create functionality
  let fieldInfo;
  try {
    // Get field info for the table
    fieldInfo = await FetchFieldNames(db, table, '0');
    
    if (!fieldInfo || fieldInfo.length === 0) {
      throw new Error("Could not fetch field information");
    }
  } catch (error) {
    console.error("Error fetching field information:", error);
    return (
      <div className="p-5">
        <h1 className="text-2xl font-bold mb-4">Error</h1>
        <p>Failed to fetch field information for the table. There might be a permission issue.</p>
      </div>
    );
  }
  
  // Prepare form fields, excluding _id (will be generated by the database)
  const editableFields = fieldInfo.filter(field => field.name !== '_id');
  
  // Display the create record form
  return (
    <div className="p-5">
      <h1 className="text-2xl font-bold mb-4">Create New Record</h1>
      <div className="mb-4">
        <p><strong>Database:</strong> {db}</p>
        <p><strong>Table:</strong> {table}</p>
      </div>
     
      <form 
        action={`/api/adminCreateRecord?redirect=/fields?db=${encodeURIComponent(db)}&table=${encodeURIComponent(table)}`} 
        method="POST" 
        className="space-y-6"
      >
        <input type="hidden" name="db" value={db} />
        <input type="hidden" name="table" value={table} />
        
        <div className="bg-base-100 shadow rounded-lg p-6">
          <div className="space-y-4">
            {editableFields.map((field) => (
              <div key={field.name} className="grid grid-cols-3 gap-4 items-center">
                <label htmlFor={field.name} className="font-medium col-span-1">{field.name}:</label>
                
                {/* Render different inputs based on field type */}
                {field.type === 'Boolean' ? (
                  <select 
                    id={field.name}
                    name={field.name}
                    className="select select-bordered w-full col-span-2"
                  >
                    <option value="">-- Select --</option>
                    <option value="true">True</option>
                    <option value="false">False</option>
                  </select>
                ) : field.type === 'Number' || field.type === 'Int' || field.type === 'Float' ? (
                  <input 
                    type="number"
                    id={field.name}
                    name={field.name}
                    className="input input-bordered w-full col-span-2"
                  />
                ) : field.type === 'Object' || field.type === 'JSON' ? (
                  <textarea
                    id={field.name}
                    name={field.name}
                    placeholder="{}"
                    rows={4}
                    className="textarea textarea-bordered w-full col-span-2 font-mono"
                  />
                ) : (
                  <input 
                    type="text"
                    id={field.name}
                    name={field.name}
                    className="input input-bordered w-full col-span-2"
                  />
                )}
              </div>
            ))}
          </div>
          
          <div className="flex justify-end mt-6 space-x-3">
            <h2 className="text-error font-bold text-lg mb-4">WARNING! This is a direct database operation.</h2>
            <NavigateBackButton />
            <button type="submit" className="btn btn-error">Create Record</button>
          </div>
        </div>
      </form>
    </div>
  );
}
